# Generated by Django 4.2 on 2023-12-31 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
